import { FileText, Globe, Layers, Palette, Smartphone, TrendingUp, Video, Wrench } from 'lucide-react'
import type { PricingCategory, PricingFaq } from '@/types/pricing-page'

export const serviceCategories = [
  {
    id: 'web',
    icon: Globe,
    title: 'Webサイト制作',
    titleEn: 'Web Design & Development',
    description: 'ブランドの世界観を反映した、成果につながるWebサイトを制作します。',
    priceRange: '15万円〜',
    services: [
      { name: 'コーポレートサイト', price: '25万円〜', note: '5〜10ページ程度' },
      { name: 'ランディングページ', price: '15万円〜', note: '1ページ構成' },
      { name: 'ECサイト', price: '50万円〜', note: 'Shopify対応可' },
      { name: 'ポートフォリオサイト', price: '20万円〜', note: '作品紹介に特化' },
      { name: 'メディアサイト', price: '40万円〜', note: 'ブログ・オウンドメディア' },
    ],
    features: ['レスポンシブ対応', 'SEO内部対策', 'SSL対応', 'お問い合わせフォーム', '修正無制限'],
  },
  {
    id: 'cms',
    icon: Layers,
    title: 'CMS構築',
    titleEn: 'CMS Development',
    description: '更新しやすく、運用しやすいCMSを構築します。',
    priceRange: '10万円〜',
    services: [
      { name: 'WordPress構築', price: '10万円〜', note: 'テーマカスタマイズ含む' },
      { name: 'microCMS構築', price: '8万円〜', note: 'ヘッドレスCMS' },
      { name: 'Notion連携サイト', price: '12万円〜', note: 'Notionをデータベースに' },
      { name: 'Movable Type構築', price: '12万円〜', note: '静的生成・企業サイト向け' },
      { name: 'Drupal構築', price: '15万円〜', note: '大規模・多言語サイト対応' },
      { name: 'オリジナルCMS', price: '25万円〜', note: '要件に合わせた開発' },
    ],
    features: ['管理画面レクチャー', 'マニュアル作成', '初期コンテンツ投入サポート', '修正無制限'],
  },
  {
    id: 'app',
    icon: Smartphone,
    title: 'アプリ開発',
    titleEn: 'App Development',
    description: 'Webアプリ・モバイルアプリの企画から開発まで対応します。',
    priceRange: '50万円〜',
    services: [
      { name: 'Webアプリケーション', price: '50万円〜', note: '要件により変動' },
      { name: 'PWA開発', price: '40万円〜', note: 'オフライン対応可' },
      { name: 'LINE公式アカウント連携', price: '15万円〜', note: 'LIFF/Messaging API' },
      { name: '業務効率化ツール', price: '25万円〜', note: '社内システム・管理ツール' },
    ],
    features: ['要件定義', 'プロトタイプ作成', 'テスト・デバッグ', '運用サポート', '修正無制限'],
  },
  {
    id: 'design',
    icon: Palette,
    title: 'デザイン',
    titleEn: 'Design',
    description: 'ロゴ、名刺、バナーなど、あらゆるデザインに対応します。',
    priceRange: '1万円〜',
    services: [
      { name: 'ロゴデザイン', price: '5万円〜', note: '3案提案・修正無制限' },
      { name: '名刺デザイン', price: '1万円〜', note: '両面・印刷手配可' },
      { name: 'バナーデザイン', price: '5,000円〜/点', note: 'Web・SNS用' },
      { name: 'UIデザイン', price: '10万円〜', note: 'Figma納品' },
      { name: 'ブランドガイドライン', price: '15万円〜', note: 'ロゴ・色・フォント規定' },
    ],
    features: ['オリジナルデザイン', '修正無制限', '各種フォーマット納品'],
  },
  {
    id: 'print',
    icon: FileText,
    title: '紙媒体',
    titleEn: 'Print Media',
    description: 'チラシ、パンフレット、ポスターなど印刷物のデザインを行います。',
    priceRange: '1万円〜',
    services: [
      { name: 'チラシ・フライヤー', price: '1万円〜', note: 'A4片面〜' },
      { name: 'パンフレット', price: '5万円〜', note: '4ページ〜' },
      { name: 'ポスター', price: '3万円〜', note: 'A2〜B1' },
      { name: '会社案内', price: '10万円〜', note: '8ページ〜' },
      { name: 'ショップカード', price: '1万円〜', note: '両面' },
    ],
    features: ['印刷入稿データ作成', '印刷手配可能', 'DICカラー対応', '修正無制限'],
  },
  {
    id: 'video',
    icon: Video,
    title: '動画制作',
    titleEn: 'Video Production',
    description: 'SNS用ショート動画から企業紹介動画まで幅広く対応します。',
    priceRange: '10万円〜',
    services: [
      { name: 'SNSショート動画', price: '10万円〜', note: '15〜60秒' },
      { name: 'サービス紹介動画', price: '25万円〜', note: '1〜3分' },
      { name: '企業紹介動画', price: '40万円〜', note: '3〜5分' },
      { name: 'モーショングラフィックス', price: '20万円〜', note: 'アニメーション' },
      { name: 'YouTube運用支援', price: '15万円〜/月', note: '企画・編集・サムネイル' },
    ],
    features: ['企画・構成', '撮影・編集', 'BGM・SE', 'テロップ', '修正無制限'],
  },
  {
    id: 'marketing',
    icon: TrendingUp,
    title: 'マーケティング',
    titleEn: 'Marketing',
    description: '集客から運用まで、Webマーケティング全般をサポートします。',
    priceRange: '3万円〜/月',
    services: [
      { name: 'SNS運用代行', price: '5万円〜/月', note: 'Instagram/X/Facebook' },
      { name: 'Web広告運用', price: '広告費の15%〜', note: 'Google/Meta広告' },
      { name: 'SEO対策', price: '3万円〜/月', note: 'コンテンツ施策含む' },
      { name: 'アクセス解析', price: '1.5万円〜/月', note: 'GA4レポート' },
      { name: 'MEO対策', price: '1.5万円〜/月', note: 'Googleマップ最適化' },
    ],
    features: ['戦略立案', '定期レポート', '改善提案', 'ミーティング対応'],
  },
  {
    id: 'support',
    icon: Wrench,
    title: '保守・運用',
    titleEn: 'Maintenance & Support',
    description: 'サイト公開後の更新・保守・改善をサポートします。',
    priceRange: '5,000円〜/月',
    services: [
      { name: 'ライトプラン', price: '5,000円/月', note: '軽微な修正・月2回まで' },
      { name: 'スタンダードプラン', price: '1.5万円/月', note: '更新代行・月5回まで' },
      { name: 'プレミアムプラン', price: '3万円/月', note: '修正無制限・優先対応' },
      { name: 'スポット対応', price: '3,000円〜/件', note: '都度のご依頼' },
    ],
    features: ['定期バックアップ', 'セキュリティ対策', 'サーバー監視', '緊急時対応'],
  },
] satisfies PricingCategory[]

export const pricingFaqs = [
  {
    question: '予算が限られているのですが、相談できますか？',
    answer: 'はい、もちろんです。ご予算に応じて、機能やページ数を調整したり、段階的に制作を進めるなど、柔軟にご提案させていただきます。まずはお気軽にご相談ください。',
  },
  {
    question: '見積りは無料ですか？',
    answer: 'はい、お見積りは無料です。ヒアリング後、ご要望に合わせた詳細なお見積りをご提示いたします。',
  },
  {
    question: '納期はどれくらいですか？',
    answer: 'プロジェクトの規模によりますが、LPで約2〜4週間、コーポレートサイトで約1〜2ヶ月が目安です。お急ぎの場合もご相談ください。',
  },
  {
    question: '支払い方法は？',
    answer: '銀行振込でのお支払いをお願いしております。基本的には着手時に50%、納品時に50%の分割払いとなります。',
  },
  {
    question: '遠方でも依頼できますか？',
    answer: 'はい、オンラインでの打ち合わせに対応しておりますので、全国どこからでもご依頼いただけます。',
  },
  {
    question: '掲載されていないサービスも依頼できますか？',
    answer: 'はい、掲載内容以外にもご要望があればお気軽にご相談ください。パートナー企業との連携により、幅広いニーズに対応可能です。',
  },
] satisfies PricingFaq[]
